### ISSUE TITLE
Add development workflow (Makefile)

### ISSUE THREAD

**Issue by takahi-i** [funwarioisii/decotra#6]
Hi @funwarioisii!  I would like to join the development of this tool. Would be very nice to have workflow for the development.

**Comment by funwarioisii** [comment]
Hi @takahi-i !
Thanks open this issue.

I prepared Makefile and a [section](https://github.com/funwarioisii/decotra#for-developer) for developer.

If you have some idea, please Pull Requests 😄

**Comment by takahi-i** [comment]
splendid @funwarioisii !
